### ISSUE TITLE
python-black: empty exclude swallows "--check"

### ISSUE THREAD

**Issue by gndrmnn** [osism/zuul-jobs#58]
If you do not use the exclude variable (default: ""), the role still inserts ``--exclude`` with no further input and therefore swallows the following ``--check`` leading to false negatives for the test.

This should be fixed by not using ``--exclude`` at all, if the variable is empty.

**Comment by sbstnnmnn** [comment]
I tested it successfully here: https://github.com/osism/ansible-collection-commons/pull/542/commits/60587af81534a253a0c08e83e88141c6f2d164f1
